"""
financial_auditor.py - Financial analysis and CEO briefing generation.

Backs the .claude/skills/financial-auditor/SKILL.md specification.
Analyzes transactions, categorizes expenses, detects anomalies, and generates reports.
"""

import json
import csv
import re
import logging
from pathlib import Path
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional, Tuple
from collections import defaultdict
import statistics

import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from config import get_settings
from utilities.vault_manager import VaultManager
from utilities.audit_logic import (
    SUBSCRIPTION_PATTERNS,
    CATEGORY_MAP,
    categorize_transaction,
    get_monthly_totals,
    find_savings_opportunities,
    generate_audit_summary,
)

logger = logging.getLogger(__name__)


class FinancialAuditor:
    """
    Financial auditor for the AI Employee system.
    
    Handles:
    - Transaction import and categorization
    - Anomaly detection
    - Metrics calculation
    - CEO Briefing generation
    - Monthly close process
    - Cash flow forecasting
    - Approval workflow integration for out-of-policy spending
    """
    
    # Anomaly detection thresholds
    ANOMALY_AMOUNT_MULTIPLIER = 3.0  # 3-sigma rule
    ANOMALY_DUPLICATE_WINDOW_HOURS = 2
    ANOMALY_WEEKEND_TRANSACTION = True
    NEW_VENDOR_THRESHOLD = 3  # Max transactions before vendor is "known"
    
    # Expense categories (expanded from audit_logic)
    EXPENSE_CATEGORIES = {
        'payroll': ['salary', 'wages', 'payroll', 'bonus', 'commission', 'contractor'],
        'cloud_infrastructure': ['aws', 'azure', 'gcp', 'digitalocean', 'heroku', 'railway', 'render', 'cloudflare'],
        'software_saas': ['notion', 'slack', 'zoom', 'dropbox', 'figma', 'canva', 'trello', 'asana', 'jira'],
        'marketing': ['google ads', 'facebook ads', 'linkedin', 'mailchimp', 'hubspot', 'semrush', 'ahrefs'],
        'communication': ['twilio', 'phone', 'video', 'conference', 'webinar'],
        'office': ['rent', 'utilities', 'supplies', 'equipment', 'furniture'],
        'travel': ['flight', 'hotel', 'uber', 'lyft', 'taxi', 'travel', 'meals'],
        'professional_services': ['legal', 'accounting', 'consulting', 'audit', 'insurance'],
        'entertainment': ['netflix', 'spotify', 'disney', 'hulu', 'audible'],
        'payment_processing': ['stripe', 'square', 'paypal', 'payment processing'],
        'banking': ['wire transfer', 'ach', 'bank fee', 'overdraft', 'interest'],
        'miscellaneous': [],
    }
    
    # CEO Briefing template
    BRIEFING_TEMPLATE = """## Monday Morning CEO Briefing

**Generated:** {generated_at}
**Period:** {period_start} to {period_end}
**Prepared by:** AI Employee Financial Auditor v1.0

---

## 📊 Executive Summary

{executive_summary}

## 💰 Revenue

{revenue_section}

## 💸 Expenses

{expense_section}

## ✅ Completed Tasks

{completed_tasks_section}

## ⚠️ Bottlenecks

{bottlenecks_section}

## 🔍 Proactive Suggestions

{suggestions_section}

## 📅 Upcoming Deadlines

{deadlines_section}

---

*Generated by AI Employee Financial Auditor*
"""
    
    def __init__(self, vault_path: str = None):
        """
        Initialize Financial Auditor.
        
        Args:
            vault_path: Path to Obsidian vault
        """
        self.settings = get_settings()
        self.vault_path = Path(vault_path) if vault_path else self.settings.vault_path
        self.vault_manager = VaultManager()
        
        # Known vendors tracking
        self._known_vendors: Dict[str, int] = {}  # vendor_name -> transaction_count
        self._vendor_first_seen: Dict[str, str] = {}
        
        # Stats
        self.stats = {
            'transactions_analyzed': 0,
            'anomalies_detected': 0,
            'briefings_generated': 0,
            'categories_updated': 0,
            'errors': 0,
            'last_analysis': None,
            'started_at': datetime.now().isoformat()
        }
    
    def import_csv_transactions(self, csv_path: str) -> List[Dict[str, Any]]:
        """
        Import transactions from CSV file.
        
        Expected CSV columns: date, description, amount, category (optional), account (optional)
        
        Args:
            csv_path: Path to CSV file
            
        Returns:
            List of parsed transaction dictionaries
        """
        transactions = []
        
        try:
            with open(csv_path, 'r', encoding='utf-8-sig') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    txn = self._normalize_csv_row(row)
                    if txn:
                        transactions.append(txn)
            
            logger.info(f"Imported {len(transactions)} transactions from {csv_path}")
            
        except FileNotFoundError:
            logger.error(f"CSV file not found: {csv_path}")
        except Exception as e:
            logger.error(f"Error importing CSV: {e}")
        
        return transactions
    
    def import_json_transactions(self, json_path: str) -> List[Dict[str, Any]]:
        """
        Import transactions from JSON file.
        
        Expected format: list of {date, description, amount, ...}
        
        Args:
            json_path: Path to JSON file
            
        Returns:
            List of transaction dictionaries
        """
        try:
            with open(json_path, 'r') as f:
                data = json.load(f)
            
            if isinstance(data, list):
                return [self._normalize_transaction(t) for t in data if t]
            elif isinstance(data, dict) and 'transactions' in data:
                return [self._normalize_transaction(t) for t in data['transactions'] if t]
            else:
                logger.warning(f"Unexpected JSON format in {json_path}")
                return []
                
        except Exception as e:
            logger.error(f"Error importing JSON: {e}")
            return []
    
    def _normalize_csv_row(self, row: Dict) -> Optional[Dict[str, Any]]:
        """Normalize a CSV row into a standard transaction format."""
        try:
            # Handle common CSV formats
            date_str = row.get('date', '') or row.get('Date', '') or row.get('transaction_date', '')
            description = row.get('description', '') or row.get('Description', '') or row.get('memo', '')
            amount_str = row.get('amount', '') or row.get('Amount', '') or row.get('value', '')
            
            if not date_str or not amount_str:
                return None
            
            # Parse amount
            amount_str = amount_str.replace(',', '').replace('$', '').replace('€', '').replace('£', '').strip()
            amount = float(amount_str)
            
            # Parse date
            date = self._parse_date(date_str)
            
            return {
                'date': date,
                'description': description.strip(),
                'amount': amount,
                'category': row.get('category', ''),
                'account': row.get('account', ''),
                'imported_at': datetime.now().isoformat()
            }
            
        except (ValueError, KeyError) as e:
            logger.debug(f"Skipping malformed CSV row: {e}")
            return None
    
    def _normalize_transaction(self, txn: Dict) -> Dict[str, Any]:
        """Normalize a transaction dictionary."""
        return {
            'date': txn.get('date', txn.get('timestamp', datetime.now().isoformat())),
            'description': txn.get('description', txn.get('memo', txn.get('note', ''))),
            'amount': float(txn.get('amount', txn.get('value', 0))),
            'category': txn.get('category', ''),
            'account': txn.get('account', ''),
            'imported_at': datetime.now().isoformat()
        }
    
    def _parse_date(self, date_str: str) -> str:
        """Parse various date formats into ISO format."""
        formats = [
            '%Y-%m-%d',
            '%m/%d/%Y',
            '%d/%m/%Y',
            '%Y/%m/%d',
            '%m-%d-%Y',
            '%d-%m-%Y',
            '%B %d, %Y',
            '%b %d, %Y',
            '%Y-%m-%dT%H:%M:%S',
            '%Y-%m-%d %H:%M:%S',
        ]
        
        for fmt in formats:
            try:
                dt = datetime.strptime(date_str.strip(), fmt)
                return dt.strftime('%Y-%m-%d')
            except ValueError:
                continue
        
        # Return as-is if no format matches
        return date_str.strip()
    
    def categorize_transaction(self, transaction: Dict[str, Any]) -> Dict[str, Any]:
        """
        Categorize a single transaction.
        
        Uses both the subscription pattern matching from audit_logic.py
        and additional expense category classification.
        
        Args:
            transaction: Transaction dict with date, description, amount
            
        Returns:
            Transaction dict with category, subcategory, and metadata
        """
        description = transaction.get('description', '').lower()
        amount = transaction.get('amount', 0)
        
        # First check subscription patterns
        sub_result = categorize_transaction(transaction)
        if sub_result:
            transaction['category'] = sub_result['category']
            transaction['subcategory'] = 'subscription'
            transaction['subscription_name'] = sub_result['name']
            return transaction
        
        # Check expense categories
        for category, keywords in self.EXPENSE_CATEGORIES.items():
            for keyword in keywords:
                if keyword in description:
                    transaction['category'] = category
                    transaction['subcategory'] = 'expense'
                    break
            if transaction.get('category'):
                break
        
        # Default category based on amount
        if not transaction.get('category'):
            if amount < 0:
                transaction['category'] = 'income'
                transaction['subcategory'] = 'revenue'
            elif amount < 50:
                transaction['category'] = 'miscellaneous'
                transaction['subcategory'] = 'small_purchase'
            else:
                transaction['category'] = 'unclassified'
                transaction['subcategory'] = 'needs_review'
        
        return transaction
    
    def categorize_transactions(self, transactions: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Categorize a batch of transactions."""
        return [self.categorize_transaction(t) for t in transactions]
    
    def detect_anomalies(self, transactions: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Detect anomalies in transaction data.
        
        Identifies:
        - Unusual amounts (>3 standard deviations from mean)
        - Duplicate transactions
        - Weekend/holiday transactions
        - New vendors
        - Rapid-fire transactions
        
        Args:
            transactions: List of categorized transactions
            
        Returns:
            List of anomaly descriptions
        """
        anomalies = []
        amounts = [t['amount'] for t in transactions if t.get('amount')]
        
        if len(amounts) < 3:
            return anomalies
        
        mean_amount = statistics.mean(amounts)
        try:
            stdev_amount = statistics.stdev(amounts)
        except statistics.StatisticsError:
            stdev_amount = 0
        
        # Track vendors
        vendor_counts = defaultdict(int)
        vendor_first_seen = {}
        
        for i, txn in enumerate(transactions):
            desc = txn.get('description', '').lower()
            amount = txn.get('amount', 0)
            date_str = txn.get('date', '')
            
            # Extract vendor name (first few words)
            vendor = ' '.join(desc.split()[:3])
            vendor_counts[vendor] += 1
            if vendor not in vendor_first_seen:
                vendor_first_seen[vendor] = date_str
            
            # Anomaly 1: Unusual amount
            if stdev_amount > 0 and abs(amount - mean_amount) > self.ANOMALY_AMOUNT_MULTIPLIER * stdev_amount:
                anomalies.append({
                    'type': 'unusual_amount',
                    'transaction': txn,
                    'detail': f"Amount ${amount:.2f} is {abs(amount - mean_amount) / stdev_amount:.1f}σ from mean (${mean_amount:.2f})",
                    'severity': 'high' if abs(amount) > 5000 else 'medium'
                })
            
            # Anomaly 2: Weekend transaction
            if self.ANOMALY_WEEKEND_TRANSACTION:
                try:
                    dt = datetime.strptime(date_str[:10], '%Y-%m-%d')
                    if dt.weekday() >= 5:  # Saturday = 5, Sunday = 6
                        anomalies.append({
                            'type': 'weekend_transaction',
                            'transaction': txn,
                            'detail': f"Transaction on {dt.strftime('%A')}",
                            'severity': 'low'
                        })
                except (ValueError, IndexError):
                    pass
            
            # Anomaly 3: Duplicate detection (same description within short window)
            if i > 0:
                prev_txn = transactions[i - 1]
                if (desc == prev_txn.get('description', '').lower() and
                    abs(amount) == abs(prev_txn.get('amount', 0))):
                    anomalies.append({
                        'type': 'possible_duplicate',
                        'transaction': txn,
                        'detail': f"Same description and amount as previous transaction",
                        'severity': 'high'
                    })
        
        # Anomaly 4: New vendors
        for vendor, first_seen in vendor_first_seen.items():
            if vendor_counts[vendor] <= self.NEW_VENDOR_THRESHOLD:
                anomalies.append({
                    'type': 'new_vendor',
                    'detail': f"New vendor '{vendor}' with {vendor_counts[vendor]} transaction(s)",
                    'severity': 'medium',
                    'vendor': vendor,
                    'first_seen': first_seen
                })
        
        self.stats['anomalies_detected'] += len(anomalies)
        return anomalies
    
    def calculate_metrics(self, transactions: List[Dict[str, Any]], period_start: str = None, period_end: str = None) -> Dict[str, Any]:
        """
        Calculate financial metrics from transactions.
        
        Args:
            transactions: List of transactions
            period_start: Start date filter
            period_end: End date filter
            
        Returns:
            Dictionary of calculated metrics
        """
        if period_start:
            transactions = [t for t in transactions if t.get('date', '') >= period_start]
        if period_end:
            transactions = [t for t in transactions if t.get('date', '') <= period_end]
        
        revenue = sum(t['amount'] for t in transactions if t['amount'] > 0)
        expenses = sum(abs(t['amount']) for t in transactions if t['amount'] < 0)
        net = revenue - expenses
        
        # Category breakdown
        by_category = defaultdict(lambda: {'revenue': 0, 'expenses': 0, 'count': 0})
        for t in transactions:
            cat = t.get('category', 'uncategorized')
            if t['amount'] > 0:
                by_category[cat]['revenue'] += t['amount']
            else:
                by_category[cat]['expenses'] += abs(t['amount'])
            by_category[cat]['count'] += 1
        
        # Month-over-month comparison
        monthly = defaultdict(lambda: {'revenue': 0, 'expenses': 0})
        for t in transactions:
            date = t.get('date', '')
            if date:
                month = date[:7]  # YYYY-MM
                if t['amount'] > 0:
                    monthly[month]['revenue'] += t['amount']
                else:
                    monthly[month]['expenses'] += abs(t['amount'])
        
        return {
            'period': {'start': period_start, 'end': period_end},
            'total_revenue': round(revenue, 2),
            'total_expenses': round(expenses, 2),
            'net_income': round(net, 2),
            'profit_margin': round((net / revenue * 100) if revenue > 0 else 0, 1),
            'transaction_count': len(transactions),
            'by_category': dict(by_category),
            'monthly_summary': dict(monthly),
            'avg_transaction_size': round(statistics.mean([t['amount'] for t in transactions]), 2) if transactions else 0,
        }
    
    def store_transactions(self, transactions: List[Dict[str, Any]], month: str = None) -> bool:
        """
        Store categorized transactions in the vault's Accounting folder.
        
        Args:
            transactions: List of categorized transactions
            month: Target month (YYYY-MM format), defaults to current month
            
        Returns:
            True if stored successfully
        """
        if month is None:
            month = datetime.now().strftime('%Y-%m')
        
        accounting_dir = self.vault_path / 'Accounting'
        accounting_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = accounting_dir / f"Current_Month.md"
        
        try:
            # Build transaction table
            lines = [
                f"# Accounting - {month}",
                "",
                f"**Last Updated:** {datetime.now().isoformat()}",
                f"**Total Transactions:** {len(transactions)}",
                "",
                "## Transactions",
                "",
                "| Date | Description | Category | Amount | Subcategory |",
                "|------|-------------|----------|--------|-------------|",
            ]
            
            for txn in transactions:
                date = txn.get('date', 'Unknown')
                desc = txn.get('description', 'Unknown')[:50]
                cat = txn.get('category', 'Uncategorized')
                amount = txn.get('amount', 0)
                subcat = txn.get('subcategory', '')
                
                lines.append(f"| {date} | {desc} | {cat} | ${amount:.2f} | {subcat} |")
            
            # Add summary
            total = sum(t['amount'] for t in transactions)
            lines.extend([
                "",
                "---",
                f"**Total:** ${total:.2f}",
                f"**Revenue:** ${sum(t['amount'] for t in transactions if t['amount'] > 0):.2f}",
                f"**Expenses:** ${sum(abs(t['amount']) for t in transactions if t['amount'] < 0):.2f}",
            ])
            
            filepath.write_text('\n'.join(lines))
            logger.info(f"Stored {len(transactions)} transactions to {filepath}")
            return True
            
        except Exception as e:
            logger.error(f"Error storing transactions: {e}")
            return False
    
    def generate_ceo_briefing(self, period_start: str, period_end: str) -> str:
        """
        Generate the Monday Morning CEO Briefing.
        
        From the hackathon PDF:
          1. Calculate weekly revenue from Accounting
          2. Analyze completed tasks from /Tasks/Done/
          3. Identify bottlenecks
          4. Find cost savings
          5. Generate briefing document
        
        Args:
            period_start: Start of period (ISO date)
            period_end: End of period (ISO date)
            
        Returns:
            The generated briefing as markdown text
        """
        # Load transactions
        accounting_file = self.vault_path / 'Accounting' / 'Current_Month.md'
        transactions = self._load_accounting_transactions(accounting_file)
        
        # Filter by period
        period_txns = [
            t for t in transactions
            if period_start <= t.get('date', '') <= period_end
        ]
        
        # Calculate metrics
        metrics = self.calculate_metrics(period_txns, period_start, period_end)
        
        # Detect anomalies
        anomalies = self.detect_anomalies(period_txns)
        
        # Load completed tasks
        completed_tasks = self._load_completed_tasks()
        
        # Find bottlenecks
        bottlenecks = self._identify_bottlenecks(completed_tasks)
        
        # Find cost savings
        savings = self._find_cost_savings(period_txns)
        
        # Build sections
        exec_summary = self._build_executive_summary(metrics, anomalies)
        revenue_section = self._build_revenue_section(metrics)
        expense_section = self._build_expense_section(metrics)
        tasks_section = self._build_completed_tasks_section(completed_tasks)
        bottlenecks_section = self._build_bottlenecks_section(bottlenecks)
        suggestions_section = self._build_suggestions_section(savings, anomalies)
        deadlines_section = self._build_deadlines_section()
        
        briefing = self.BRIEFING_TEMPLATE.format(
            generated_at=datetime.now().strftime('%Y-%m-%d %H:%M UTC'),
            period_start=period_start,
            period_end=period_end,
            executive_summary=exec_summary,
            revenue_section=revenue_section,
            expense_section=expense_section,
            completed_tasks_section=tasks_section,
            bottlenecks_section=bottlenecks_section,
            suggestions_section=suggestions_section,
            deadlines_section=deadlines_section,
        )
        
        # Save briefing to vault
        briefings_dir = self.vault_path / 'Briefings'
        briefings_dir.mkdir(parents=True, exist_ok=True)
        
        briefing_filename = f"{period_end}_CEO_Briefing.md"
        briefing_path = briefings_dir / briefing_filename
        briefing_path.write_text(briefing)
        
        self.stats['briefings_generated'] += 1
        self.stats['last_analysis'] = datetime.now().isoformat()
        
        logger.info(f"Generated CEO Briefing: {briefing_path}")
        
        return briefing
    
    def _load_accounting_transactions(self, filepath: Path) -> List[Dict[str, Any]]:
        """Load transactions from accounting markdown file."""
        transactions = []
        
        if not filepath.exists():
            return transactions
        
        try:
            content = filepath.read_text()
            # Parse markdown table
            in_table = False
            for line in content.split('\n'):
                if line.strip().startswith('| Date'):
                    in_table = True
                    continue
                if in_table and line.strip().startswith('|---'):
                    continue
                if in_table and line.strip().startswith('|'):
                    parts = [p.strip() for p in line.split('|')[1:-1]]
                    if len(parts) >= 4:
                        try:
                            date = parts[0]
                            desc = parts[1]
                            amount_str = parts[3].replace('$', '').replace(',', '')
                            amount = float(amount_str)
                            transactions.append({
                                'date': date,
                                'description': desc,
                                'amount': amount,
                                'category': parts[2] if len(parts) > 2 else ''
                            })
                        except (ValueError, IndexError):
                            continue
                elif in_table and not line.strip().startswith('|'):
                    break
        except Exception as e:
            logger.error(f"Error loading accounting file: {e}")
        
        return transactions
    
    def _load_completed_tasks(self) -> List[Dict[str, Any]]:
        """Load completed tasks from the Done folder."""
        tasks = []
        done_dir = self.vault_path / 'Done'
        
        if not done_dir.exists():
            return tasks
        
        for task_file in done_dir.glob('*.md'):
            try:
                content = task_file.read_text()
                # Parse frontmatter
                if content.startswith('---'):
                    parts = content.split('---', 2)
                    if len(parts) >= 3:
                        metadata = {}
                        for line in parts[1].split('\n'):
                            if ':' in line:
                                k, v = line.split(':', 1)
                                metadata[k.strip()] = v.strip()
                        
                        tasks.append({
                            'file': task_file.name,
                            'type': metadata.get('type', 'unknown'),
                            'priority': metadata.get('priority', 'normal'),
                            'source': metadata.get('source', ''),
                        })
            except Exception:
                continue
        
        return tasks
    
    def _identify_bottlenecks(self, tasks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Identify bottlenecks from completed tasks."""
        bottlenecks = []
        
        # Group by type
        by_type = defaultdict(list)
        for t in tasks:
            by_type[t.get('type', 'unknown')].append(t)
        
        # Check for types with many high-priority items
        for task_type, items in by_type.items():
            high_count = sum(1 for i in items if i.get('priority') in ('critical', 'high'))
            if high_count > len(items) * 0.5 and len(items) > 3:
                bottlenecks.append({
                    'type': task_type,
                    'total': len(items),
                    'high_priority': high_count,
                    'detail': f"{high_count}/{len(items)} tasks were high priority"
                })
        
        return bottlenecks
    
    def _find_cost_savings(self, transactions: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Find potential cost savings from transaction analysis."""
        # Use audit_logic functions
        total_by_sub = defaultdict(float)
        for t in transactions:
            if t['amount'] < 0:
                sub = categorize_transaction(t)
                if sub:
                    total_by_sub[sub['name']] += t['amount']
        
        savings = {
            'unused_subscriptions': [],
            'cost_optimization': [],
            'total_potential_savings': 0.0
        }
        
        # Flag subscriptions over $100/month for review
        for name, total in total_by_sub.items():
            monthly = abs(total)
            if monthly > 100:
                savings['cost_optimization'].append({
                    'name': name,
                    'monthly_cost': round(monthly, 2),
                    'suggestion': 'Review necessity'
                })
        
        savings['total_potential_savings'] = round(sum(
            s['monthly_cost'] * 0.1 for s in savings['cost_optimization']
        ), 2)
        
        return savings
    
    def _build_executive_summary(self, metrics: Dict, anomalies: List) -> str:
        """Build executive summary section."""
        anomaly_count = len(anomalies)
        anomaly_str = f"{anomaly_count} anomalies detected" if anomaly_count > 0 else "No anomalies"
        
        return f"""This week, the AI Employee processed **{metrics['transaction_count']} transactions**
totaling **${metrics['total_revenue']:,.2f}** in revenue and **${metrics['total_expenses']:,.2f}** in expenses,
resulting in a net income of **${metrics['net_income']:,.2f}** ({metrics['profit_margin']}% margin).

{anomaly_str} requiring attention."""
    
    def _build_revenue_section(self, metrics: Dict) -> str:
        """Build revenue section."""
        return f"""**Weekly Revenue:** ${metrics['total_revenue']:,.2f}
**Monthly Run Rate:** ${metrics['total_revenue'] * 4:,.2f}
**Profit Margin:** {metrics['profit_margin']}%"""
    
    def _build_expense_section(self, metrics: Dict) -> str:
        """Build expense breakdown section."""
        lines = ["**Expense Breakdown:**"]
        for cat, data in sorted(metrics['by_category'].items(), key=lambda x: -x[1]['expenses']):
            if data['expenses'] > 0:
                lines.append(f"- **{cat.title()}:** ${data['expenses']:,.2f} ({data['count']} transactions)")
        return '\n'.join(lines)
    
    def _build_completed_tasks_section(self, tasks: List[Dict]) -> str:
        """Build completed tasks section."""
        if not tasks:
            return "No completed tasks this period."
        
        lines = [f"**{len(tasks)} tasks completed:**"]
        by_type = defaultdict(int)
        for t in tasks:
            by_type[t.get('type', 'other')] += 1
        
        for task_type, count in sorted(by_type.items(), key=lambda x: -x[1]):
            lines.append(f"- {task_type}: {count}")
        
        return '\n'.join(lines)
    
    def _build_bottlenecks_section(self, bottlenecks: List[Dict]) -> str:
        """Build bottlenecks section."""
        if not bottlenecks:
            return "No significant bottlenecks identified."
        
        lines = []
        for b in bottlenecks:
            lines.append(f"- **{b['type']}**: {b['detail']}")
        
        return '\n'.join(lines)
    
    def _build_suggestions_section(self, savings: Dict, anomalies: List) -> str:
        """Build proactive suggestions section."""
        lines = []
        
        if savings['cost_optimization']:
            lines.append("### Cost Optimization")
            for item in savings['cost_optimization']:
                lines.append(f"- **{item['name']}**: ${item['monthly_cost']:.2f}/mo — {item['suggestion']}")
        
        high_anomalies = [a for a in anomalies if a.get('severity') == 'high']
        if high_anomalies:
            lines.append("\n### ⚠️ Requiring Review")
            for a in high_anomalies[:5]:
                lines.append(f"- {a['detail']}")
        
        if not lines:
            lines.append("No actionable suggestions at this time.")
        
        return '\n'.join(lines)
    
    def _build_deadlines_section(self) -> str:
        """Build upcoming deadlines section."""
        # Check for deadline-related files or tasks
        deadlines = []
        
        # Look for tasks with deadline info
        tasks_dir = self.vault_path / 'Tasks'
        if tasks_dir.exists():
            for f in tasks_dir.glob('*.md'):
                try:
                    content = f.read_text()
                    if 'deadline' in content.lower():
                        deadlines.append(f"- {f.stem}")
                except Exception:
                    continue
        
        if deadlines:
            return '\n'.join(deadlines)
        return "No upcoming deadlines tracked."
    
    def daily_analysis(self):
        """Run daily transaction analysis."""
        today = datetime.now().strftime('%Y-%m-%d')
        accounting_file = self.vault_path / 'Accounting' / f"{today}.json"
        
        if accounting_file.exists():
            with open(accounting_file) as f:
                transactions = json.load(f)
            
            categorized = self.categorize_transactions(transactions)
            anomalies = self.detect_anomalies(categorized)
            
            # Store results
            self.store_transactions(categorized, today[:7])
            
            # Log any critical anomalies
            for anomaly in anomalies:
                if anomaly.get('severity') == 'high':
                    self.vault_manager.log_event(
                        event_type='anomaly_detected',
                        task_id='financial',
                        details={'anomaly': anomaly}
                    )
    
    def weekly_briefing(self):
        """Generate weekly CEO briefing."""
        today = datetime.now()
        monday = today - timedelta(days=today.weekday())
        last_monday = monday - timedelta(days=7)
        
        return self.generate_ceo_briefing(
            last_monday.strftime('%Y-%m-%d'),
            (monday - timedelta(days=1)).strftime('%Y-%m-%d')
        )
    
    def monthly_close(self, year: int, month: int) -> str:
        """
        Perform monthly close process.
        
        Args:
            year: Year of the month to close
            month: Month to close (1-12)
            
        Returns:
            Summary of monthly close results
        """
        period_start = f"{year}-{month:02d}-01"
        if month == 12:
            period_end = f"{year}-12-31"
        else:
            period_end = f"{year}-{month+1:02d}-01"
        
        # Generate detailed report
        metrics = self.calculate_metrics([], period_start, period_end)
        
        # Update dashboard
        accounting_file = self.vault_path / 'Accounting' / 'Current_Month.md'
        if accounting_file.exists():
            content = accounting_file.read_text()
            content = content.replace(
                f"**Last Updated:**",
                f"**Monthly Close:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}\n**Last Updated:**"
            )
            accounting_file.write_text(content)
        
        return f"Monthly close complete for {year}-{month:02d}"
    
    def cash_flow_forecast(self, months_ahead: int = 3) -> Dict[str, Any]:
        """
        Generate cash flow forecast.
        
        Args:
            months_ahead: Number of months to forecast
            
        Returns:
            Forecast data with scenarios
        """
        # Use historical data for projection
        accounting_dir = self.vault_path / 'Accounting'
        monthly_data = {}
        
        for f in accounting_dir.glob('*.md'):
            if f.name.startswith('202'):
                try:
                    monthly_data[f.stem] = self._extract_monthly_summary(f)
                except Exception:
                    continue
        
        if not monthly_data:
            return {'error': 'Insufficient historical data', 'months': []}
        
        # Calculate averages
        revenues = [d.get('revenue', 0) for d in monthly_data.values()]
        expenses = [d.get('expenses', 0) for d in monthly_data.values()]
        
        avg_revenue = statistics.mean(revenues) if revenues else 0
        avg_expenses = statistics.mean(expenses) if expenses else 0
        
        # Generate scenarios
        forecast = {'months': []}
        today = datetime.now()
        
        for i in range(1, months_ahead + 1):
            month_date = today + timedelta(days=30 * i)
            month_key = month_date.strftime('%Y-%m')
            
            # Base case, optimistic, pessimistic
            base_rev = avg_revenue
            opt_rev = avg_revenue * 1.15
            pess_rev = avg_revenue * 0.85
            
            forecast['months'].append({
                'month': month_key,
                'base_case': {
                    'revenue': round(base_rev, 2),
                    'expenses': round(avg_expenses, 2),
                    'net': round(base_rev - avg_expenses, 2)
                },
                'optimistic': {
                    'revenue': round(opt_rev, 2),
                    'expenses': round(avg_expenses * 0.95, 2),
                    'net': round(opt_rev - avg_expenses * 0.95, 2)
                },
                'pessimistic': {
                    'revenue': round(pess_rev, 2),
                    'expenses': round(avg_expenses * 1.05, 2),
                    'net': round(pess_rev - avg_expenses * 1.05, 2)
                }
            })
        
        return forecast
    
    def _extract_monthly_summary(self, filepath: Path) -> Dict[str, float]:
        """Extract revenue/expense totals from monthly accounting file."""
        summary = {'revenue': 0, 'expenses': 0}
        
        try:
            content = filepath.read_text()
            
            # Look for summary lines
            for line in content.split('\n'):
                if 'Revenue' in line or 'revenue' in line:
                    match = re.search(r'\$([0-9,]+(?:\.\d+)?)', line)
                    if match:
                        summary['revenue'] = float(match.group(1).replace(',', ''))
                elif 'Expenses' in line or 'expenses' in line or 'Expense' in line:
                    match = re.search(r'\$([0-9,]+(?:\.\d+)?)', line)
                    if match:
                        summary['expenses'] = float(match.group(1).replace(',', ''))
        except Exception:
            pass
        
        return summary
    
    def get_stats(self) -> Dict[str, Any]:
        """Return auditor statistics."""
        return {
            **self.stats,
            'known_vendors': len(self._known_vendors),
            'uptime_seconds': (datetime.now() - datetime.fromisoformat(self.stats['started_at'])).total_seconds()
        }


# ─── Standalone Execution ────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description='Financial Auditor')
    parser.add_argument('--vault-path', default='AI_Employee_Vault', help='Vault path')
    parser.add_argument('--import-csv', help='Import transactions from CSV')
    parser.add_argument('--import-json', help='Import transactions from JSON')
    parser.add_argument('--briefing', action='store_true', help='Generate CEO Briefing')
    parser.add_argument('--forecast', action='store_true', help='Generate cash flow forecast')
    parser.add_argument('--test', action='store_true', help='Run self-test')
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose output')
    
    args = parser.parse_args()
    
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    auditor = FinancialAuditor(vault_path=args.vault_path)
    
    if args.import_csv:
        txns = auditor.import_csv_transactions(args.import_csv)
        print(f"Imported {len(txns)} transactions")
        categorized = auditor.categorize_transactions(txns)
        print(f"Categorized: {len([t for t in categorized if t.get('category')])} transactions")
        for t in categorized:
            print(f"  {t['date']} | {t['description'][:40]} | {t.get('category', '?')} | ${t['amount']:.2f}")
    
    if args.import_json:
        txns = auditor.import_json_transactions(args.import_json)
        print(f"Imported {len(txns)} transactions from JSON")
    
    if args.briefing:
        today = datetime.now()
        monday = today - timedelta(days=today.weekday())
        last_monday = monday - timedelta(days=7)
        briefing = auditor.generate_ceo_briefing(
            last_monday.strftime('%Y-%m-%d'),
            (monday - timedelta(days=1)).strftime('%Y-%m-%d')
        )
        print(briefing)
    
    if args.forecast:
        forecast = auditor.cash_flow_forecast()
        print(json.dumps(forecast, indent=2, default=str))
    
    if args.test:
        print("=" * 60)
        print("Financial Auditor Self-Test")
        print("=" * 60)
        
        # Test 1: Categorize transaction
        txn = {
            'date': '2026-01-07',
            'description': 'SPOTIFY.COM BILL SUBSCRIPTION',
            'amount': -9.99
        }
        result = auditor.categorize_transaction(txn)
        assert result.get('category') in ('Entertainment', 'subscription'), f"Got: {result.get('category')}"
        print(f"✓ Categorized Spotify as: {result.get('category')}")
        
        # Test 2: Anomaly detection
        txns = [
            {'date': '2026-01-01', 'description': 'Normal expense', 'amount': -50.0},
            {'date': '2026-01-02', 'description': 'Normal expense', 'amount': -45.0},
            {'date': '2026-01-03', 'description': 'Anomaly', 'amount': -5000.0},
            {'date': '2026-01-04', 'description': 'Normal expense', 'amount': -55.0},
        ]
        categorized = auditor.categorize_transactions(txns)
        anomalies = auditor.detect_anomalies(categorized)
        assert len(anomalies) > 0, "Should detect the $5000 anomaly"
        print(f"✓ Detected {len(anomalies)} anomalies (including $5000 outlier)")
        
        # Test 3: Metrics calculation
        metrics = auditor.calculate_metrics(
            categorized, '2026-01-01', '2026-01-04'
        )
        assert metrics['total_expenses'] > 0
        assert metrics['transaction_count'] == 4
        print(f"✓ Calculated metrics: {metrics['transaction_count']} txns, ${metrics['total_expenses']:.2f} expenses")
        
        # Test 4: Cost savings
        savings = auditor._find_cost_savings(categorized)
        print(f"✓ Found cost savings opportunities: ${savings['total_potential_savings']:.2f}/mo potential")
        
        # Test 5: Date parsing
        test_dates = [
            ('2026-01-15', '2026-01-15'),
            ('01/15/2026', '2026-01-15'),
            ('15/01/2026', '2026-01-15'),
            ('January 15, 2026', '2026-01-15'),
        ]
        for input_date, expected in test_dates:
            result = auditor._parse_date(input_date)
            assert result == expected, f"Expected {expected}, got {result} for {input_date}"
        print("✓ Date parsing works for all formats")
        
        print("\n✓ All Financial Auditor tests passed!")
        print(f"\nStats: {json.dumps(auditor.get_stats(), indent=2, default=str)}")